# Source-font assets are content-pinned, not bundled in this source distribution.
# Called before dependency compilation. Existing files are never overwritten.
# A local copy may be supplied via -DSOH_SOURCE_FONTS_DIR=<original/fonts/folder>.
function(soh_restore_source_fonts manifest destination)
    file(READ "${manifest}" _manifest)
    string(JSON _count LENGTH "${_manifest}" files)
    math(EXPR _last "${_count} - 1")
    file(MAKE_DIRECTORY "${destination}")
    foreach(_index RANGE 0 ${_last})
        string(JSON _name GET "${_manifest}" files ${_index} name)
        string(JSON _expected GET "${_manifest}" files ${_index} sha256)
        string(JSON _url GET "${_manifest}" files ${_index} url)
        if(NOT _name MATCHES "^[A-Za-z0-9_-]+[.](ttf|otf)$")
            message(FATAL_ERROR "Invalid source-font manifest entry.")
        endif()
        set(_target "${destination}/${_name}")
        if(EXISTS "${_target}")
            file(SHA256 "${_target}" _actual)
            if(NOT _actual STREQUAL _expected)
                message(FATAL_ERROR "Existing ${_name} does not match the snapshot. It was NOT overwritten. Keep your original and supply the matching file from your original source.")
            endif()
            continue()
        endif()
        set(_partial "${_target}.partial")
        if(DEFINED SOH_SOURCE_FONTS_DIR AND EXISTS "${SOH_SOURCE_FONTS_DIR}/${_name}")
            file(COPY_FILE "${SOH_SOURCE_FONTS_DIR}/${_name}" "${_partial}")
        else()
            message(STATUS "Fetching source font ${_name} (SHA-256 pinned)")
            file(DOWNLOAD "${_url}" "${_partial}" STATUS _status
                TLS_VERIFY ON TIMEOUT 30 INACTIVITY_TIMEOUT 10)
            list(GET _status 0 _code)
            if(NOT _code EQUAL 0)
                file(REMOVE "${_partial}")
                message(FATAL_ERROR "Could not retrieve ${_name}: ${_status}. No game compilation started. Check network access, or use -DSOH_SOURCE_FONTS_DIR pointing to the fonts folder in the original source copy.")
            endif()
        endif()
        file(SHA256 "${_partial}" _actual)
        if(NOT _actual STREQUAL _expected)
            file(REMOVE "${_partial}")
            message(FATAL_ERROR "SHA-256 mismatch for ${_name}; the downloaded/local file was rejected. Upstream content may have changed. Use matching fonts from the original source, not an arbitrary substitute.")
        endif()
        file(RENAME "${_partial}" "${_target}")
    endforeach()
endfunction()
